name: CI

on:
  push:
    branches:
      - master
      - tests
    paths:
      - 'nux/'
      - '.github/workflows/**'
      - 'setup.py'
  pull_request:
    branches:
      - master
      - tests
    paths:
      - 'nux/'
      - '.github/workflows/**'
      - 'setup.py'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.7', '3.8']
        os: [ubuntu-latest]
    
    steps:
      - uses: actions/checkout@v1.0.0
      - name: "Set up Python"
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: "Install NuX"
        run: |
            python -m pip install --upgrade pip
            pip install wheel
            pip install -r requirements.txt
            python setup.py install
      - name: "Run all tests"
        run: |
            cd nux/tests
            for file in *test.py; do python $file; done
        shell: bash
